### ISSUE TITLE
能否加入tg推送

### ISSUE THREAD

**Issue by wukibaka** [v50-one/CloudflareSpeedTest-api#1]
### 功能需求

更新完IP后推送到tg
可以自定义botapi

### 预期目标

如图
![Screenshot_20230420_025716_uz unnarsx cherrygram_edit_270278835906154](https://user-images.githubusercontent.com/51240031/233173950-3f870430-6847-4446-b89a-ff7cab5af2c7.jpg)

**Comment by x6nux** [comment]
新版已加上

**Comment by wukibaka** [comment]
> 新版已加上

可以加入自定义tgbotapi镜像吗 国内机子没法直连tgbotapi
